import_all(graphics)
import_all(ocr)
import_all(iulib)

input = bytearray()
read_image_gray(input,arg[1])
make_page_black(input)
deskew = make_DeskewPageByRAST()
image = bytearray()
deskew:cleanup(image,input)
segmentation = intarray()
segmenter = make_SegmentPageByRAST()
segmenter:segment(segmentation,image)
check_page_segmentation(segmentation)
simple_recolor(segmentation)
write_image_packed(arg[2],segmentation)
